### ISSUE TITLE
In Advection.jl surface terms and Vmap not of the same dimension

### ISSUE THREAD

**Issue by fxgiraldo** [climate-machine/Canary.jl#26]
In Advection-1d I ran into the problem of having to reshape nx and sJ as it is not of the same dimension (or rather shape) of vmap.  Not a big deal but probably need to have them shaped similarly.

**Comment by jkozdon** [comment]
I'll work on fixing this. I'll make the surface metrics match the storage of `vmapM` and `vmapP`. Right now the first indices of the surface metrics using Cartesian indices, so I will flatten this out so that its linear indexing.
